export default [
  {
    title: "Documentation in Design Systems (panel discussion)",
    url_info: "https://infa.ai/events/documentation_20250807",
    url_slides: "https://infa.ai/events/documentation_20250807",
    talk: "craft-across-ds-documentation",
    type: "professional",
    event: "Craft Across",
    year: 2025,
    featured: false,
  },
  {
    title: "Design Systems Aren't Hard",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/design-systems-arent-hard-a5a1f88d-e8fe-46de-861c-40cf9e12be47",
    talk: "design-systems-arent-hard",
    type: "professional",
    event: "That Conference TX",
    year: 2022,
    featured: false,
  },
  {
    title: "Design Systems Aren't Hard",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/design-systems-arent-hard-df49e240-1ce5-44ea-a9c2-8cb30f7bac16",
    talk: "design-systems-arent-hard",
    type: "professional",
    event: "WebOps by Pantheon",
    year: 2021,
    featured: false,
  },
  {
    title: "Design Systems Aren't Hard",
    url_slides: "https://speakerdeck.com/milsyobtaf/design-systems-arent-hard",
    talk: "design-systems-arent-hard",
    type: "professional",
    event: "OpenJS",
    year: 2020,
    featured: true,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-6",
    talk: "digital-speakeasy",
    type: "professional",
    event: "DrupalCon Nashville",
    year: 2018,
    featured: true,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/opening-the-black-box-7fad229c-b83e-499e-bb3d-5923f80014ff",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "NERDSummit",
    year: 2018,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/become-a-better-developer-with-debugging-1",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "Texas Camp",
    year: 2018,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-6",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "[php]World",
    year: 2017,
    featured: true,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-5",
    talk: "digital-speakeasy",
    type: "professional",
    event: "[php]World",
    year: 2017,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-7",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "NEDCamp",
    year: 2017,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-5",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "DrupalCamp Cornell",
    year: 2017,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-4",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "DrupalCamp Montréal",
    year: 2017,
    featured: false,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-3",
    talk: "digital-speakeasy",
    type: "professional",
    event: "DrupalCamp Montréal",
    year: 2017,
    featured: false,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-1",
    talk: "digital-speakeasy",
    type: "professional",
    event: "NERDSummit",
    year: 2017,
    featured: false,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-4",
    talk: "digital-speakeasy",
    type: "professional",
    event: "Design4Drupal",
    year: 2017,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-3",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "DrupalCamp Northern Lights",
    year: 2017,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-2",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "DrupalCamp NJ",
    year: 2017,
    featured: false,
  },
  {
    title: "Nearly Headless Drupal",
    url_slides: "https://speakerdeck.com/milsyobtaf/nearly-headless-drupal-1",
    talk: "nearly-headless",
    type: "professional",
    event: "SANDCamp",
    year: 2016,
    featured: false,
  },
  {
    title: "Becoming a Better Developer Through Debugging",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/become-a-better-developer-with-debugging-techniques-for-drupal-and-more",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "SANDCamp",
    year: 2016,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box-1",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "DrupalCamp CT",
    year: 2016,
    featured: false,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website",
    talk: "digital-speakeasy",
    type: "professional",
    event: "DrupalCamp CT",
    year: 2016,
    featured: false,
  },
  {
    title: "The Digital Speakeasy: Secure and Anonymous Access to Your Website",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-digital-speakeasy-secure-and-anonymous-access-to-your-website-2",
    talk: "digital-speakeasy",
    type: "professional",
    event: "BADCamp",
    year: 2016,
    featured: false,
  },
  {
    title: "Nearly Headless Drupal",
    url_slides: "https://speakerdeck.com/milsyobtaf/nearly-headless-drupal",
    talk: "nearly-headless",
    type: "professional",
    event: "NYCCamp",
    year: 2015,
    featured: false,
  },
  {
    title: "Nearly Headless Drupal",
    url_slides: "https://speakerdeck.com/milsyobtaf/nearly-headless-drupal-2",
    talk: "nearly-headless",
    type: "professional",
    event: "NERDSummit",
    year: 2015,
    featured: false,
  },
  {
    title: "DNS: What Do All These Letters Mean?!?!?!",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/dns-what-do-all-these-letters-actually-mean",
    talk: "dns-what-do-they-mean",
    type: "professional",
    event: "NERDSummit",
    year: 2015,
    featured: false,
  },
  {
    title:
      "Opening the Black Box: Becoming a Better Developer Through Debugging",
    url_slides: "https://speakerdeck.com/milsyobtaf/opening-the-black-box",
    talk: "blackbox-better-developer",
    type: "professional",
    event: "BADCamp",
    year: 2015,
    featured: false,
  },
  {
    title: "The Top Ten Development Lessons They Didn't Teach You In School",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-top-ten-development-lessons-they-didnt-teach-you-in-school",
    talk: "top-ten-lessons",
    type: "professional",
    event: "NERDSummit",
    year: 2014,
    featured: false,
  },
  {
    title: "The Top Ten Development Lessons They Didn't Teach You In School",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/the-top-ten-development-lessons-they-didnt-teach-you-in-school-1",
    talk: "top-ten-lessons",
    type: "professional",
    event: "DrupalCamp CT",
    year: 2014,
    featured: false,
  },
  {
    title: "Days of Future Past: A Brief History of the Internet",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/days-of-future-past-a-brief-history-of-the-internet",
    talk: "future-past",
    type: "academic",
    event: "University of Incarnate Word Convergent Media",
    year: 2014,
    featured: false,
  },
  {
    title: "Yet Another Hours Module",
    url_slides: "https://speakerdeck.com/milsyobtaf/yet-another-hours-module",
    talk: "hours-module",
    type: "professional",
    event: "UT Austin Drupal Users Group",
    year: 2014,
    featured: false,
  },
  {
    title: "Remodeling Antique Plumbing with Modern Tools",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/remodeling-antique-plumbing-with-modern-tools",
    talk: "antique-plumbing",
    type: "professional",
    event: "DrupalCamp Austin",
    year: 2013,
    featured: false,
  },
  {
    title: "A Fool Proof Three Step Path to Unlimited Viral Internet Success!!",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/a-fool-proof-three-step-path-to-unlimited-viral-internet-success",
    talk: "three-step-path",
    type: "academic",
    event: "University of Incarnate Word Convergent Media",
    year: 2012,
    featured: false,
  },
  {
    title: "Pardon My Paranoia: Personal Privacy and the Economics of Startups",
    url_slides:
      "https://speakerdeck.com/milsyobtaf/pardon-my-paranoia-personal-privacy-and-the-economics-of-startups",
    talk: "pardon-paranoia",
    type: "academic",
    event: "University of Incarnate Word Convergent Media",
    year: 2012,
    featured: false,
  },
]
