name: Build and Deploy 11ty

on:
  push:
    branches:
      - primary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
            version: 10

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: pnpm install && pnpm run build
        run: |
          pnpm install
          pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
